# Generated by Django 5.0.7 on 2024-08-01 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
